# Generated by Django 5.1.7 on 2025-05-09 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RegistroEmprendedores', '0006_remove_product_image_product_image_url'),
        ('negocios', '0002_entrepreneur_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['name'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('RegistroEmprendedores.product',),
        ),
    ]
