# Generated by Django 5.1.7 on 2025-05-03 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistroEmprendedores', '0003_categoria_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='\\cuentas\\static\\cuentas\\img'),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
