# Generated by Django 5.1.7 on 2025-05-02 03:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('RegistroEmprendedores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrepreneur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('lunes_inicio', models.TimeField(blank=True, null=True)),
                ('lunes_fin', models.TimeField(blank=True, null=True)),
                ('martes_inicio', models.TimeField(blank=True, null=True)),
                ('martes_fin', models.TimeField(blank=True, null=True)),
                ('miercoles_inicio', models.TimeField(blank=True, null=True)),
                ('miercoles_fin', models.TimeField(blank=True, null=True)),
                ('jueves_inicio', models.TimeField(blank=True, null=True)),
                ('jueves_fin', models.TimeField(blank=True, null=True)),
                ('viernes_inicio', models.TimeField(blank=True, null=True)),
                ('viernes_fin', models.TimeField(blank=True, null=True)),
                ('contact_info', models.CharField(blank=True, max_length=255, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='cuentas/img/')),
                ('entrepreneur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='RegistroEmprendedores.entrepreneur')),
            ],
        ),
    ]
