# Generated by Django 5.1.7 on 2025-05-03 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistroEmprendedores', '0004_alter_product_category_alter_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products/images/'),
        ),
    ]
