# Generated by Django 5.1.6 on 2025-04-06 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0004_remove_usuario_username_usuario_nombre_completo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenCarrusel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('imagen', models.ImageField(upload_to='carrusel/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre_completo',
            field=models.CharField(default='', max_length=150, unique=True),
        ),
    ]
